import chalk from 'chalk';
import type { Command } from 'commander';
import TOPICS from '../guide/index.ts';

export function topicNames(): string[] {
  return Object.keys(TOPICS);
}

const COMMAND_NOTATION = 'Commands use `stim`. If it is not installed globally, replace `stim` with `npx stim-cli`.';

export function renderTopic(name: string): string | null {
  const topic = TOPICS[name];
  if (!topic) return null;
  return `${COMMAND_NOTATION}\n\n${topic.body()}`;
}

export function renderIndex(version: string): string {
  const lines = [
    `stim ${version} -- reference for the binary you are running.`,
    '',
    COMMAND_NOTATION,
    '',
    'This output is generated by the CLI, so it always matches this version.',
    'The bundled skill routes coding agents to the agent topic. Other topics',
    'carry the detailed command contracts and remedies.',
    '',
    'TOPICS',
  ];
  const width = Math.max(...topicNames().map((n) => n.length));
  for (const name of topicNames()) {
    lines.push(`  ${name.padEnd(width)}  ${TOPICS[name]?.summary ?? ''}`);
  }
  lines.push('', 'Read one with:  stim guide <topic>');
  return lines.join('\n');
}

export default function guideCommand(program: Command, version: string): void {
  program
    .command('guide [topic]')
    .description(
      'Print reference documentation for THIS version of Stim (topics: ' +
        topicNames().join(', ') +
        '). Generated by the binary, so it cannot drift from the installed CLI.',
    )
    .action((topic) => {
      if (!topic) {
        console.log(renderIndex(version));
        return;
      }
      const body = renderTopic(topic);
      if (!body) {
        console.error(chalk.red(`Unknown topic "${topic}".`));
        console.error(chalk.dim(`Available: ${topicNames().join(', ')}`));
        process.exit(1);
      }
      console.log(body);
    });
}
