// Generates the loop documentation a repo needs before several agents can work
// in it at once.
//
// Deliberately not a scaffolder for scripts: `worktree create --carry-ignored`
// and `worktree remove` already are the workspace lifecycle, so generating a
// wrapper around them would be code to maintain in every consuming repo. What a
// repo cannot get from `--help` is the ORDER, and the handful of traps that cost
// an afternoon each -- so that is what gets written down.
//
// Everything here is a pure function of facts about the project, so the template
// can be tested without touching a filesystem.

// Detected rather than assumed: the advice differs enough between an Expo app
// and a bare one that guessing would produce a document that is wrong in the
// places people actually get stuck.
export function projectFacts({ pkg, appConfig, hasPodfile }) {
  const deps = { ...(pkg?.dependencies || {}), ...(pkg?.devDependencies || {}) };
  const expoRange = deps.expo || null;
  const sdkMajor = expoRange
    ? parseInt(String(expoRange).replace(/[^\d.]/g, '').split('.')[0], 10) || null
    : null;
  return {
    name: appConfig?.expo?.name || pkg?.name || 'the app',
    isExpo: Boolean(expoRange),
    sdkMajor,
    hasDevClient: Boolean(deps['expo-dev-client']),
    hasPodfile: Boolean(hasPodfile),
    // The run command is the one thing rn-iso refuses to decide at runtime, so
    // the template states the project's own rather than inventing one.
    runCommand: expoRange ? 'npx expo run:ios' : 'npx react-native run-ios',
  };
}

function devClientSection(facts) {
  if (!facts.isExpo) {
    return `A reserved port reaches a bare React Native app through \`RCT_METRO_PORT\`
at build time or \`RCT_jsLocation\` at runtime. Prefer the runtime one: a build
cache keys on the native fingerprint, which does not include the port, so a
binary with a port compiled in can be handed to a workspace holding a different
one and will silently talk to the wrong bundler.

\`\`\`bash
xcrun simctl spawn <udid> defaults write <bundle-id> RCT_jsLocation "localhost:<port>"
\`\`\``;
  }
  if (facts.hasDevClient) {
    return `A reserved port only reaches the app because \`expo-dev-client\` is installed:
\`--port\` is never compiled into the binary, it travels in the deep link
\`run:ios\` opens. Keeping the port out of the binary is also what lets one
cached build serve workspaces holding different ports.`;
  }
  return `**Install \`expo-dev-client\` before anything else here works.** A reserved
port cannot reach the app without it -- \`--port\` travels in the deep link
\`run:ios\` opens, and with nothing handling that URL the app looks for Metro on
8081, finds nothing, and shows a red \`No script URL provided\`.

\`\`\`bash
npx expo install expo-dev-client
\`\`\``;
}

function buildCacheSection(facts) {
  if (facts.isExpo) {
    const key = facts.sdkMajor && facts.sdkMajor <= 53
      ? 'expo.experiments.buildCacheProvider'
      : 'expo.buildCacheProvider';
    return `Most changes touch no native input, and those should not compile anything.
\`@rn-iso/expo-build-cache\` keys a built \`.app\` on Expo's fingerprint of the
native inputs and installs it instead of building.

\`\`\`bash
npm i -D @rn-iso/expo-build-cache
\`\`\`

Point \`${key}\` at it in app.json. That key matters: SDK 53 reads only the
\`experiments\` one and ignores the top-level one in silence, while SDK 54+ reads
the top-level one and falls back to \`experiments\`.

Watch for \`[build-cache] hit\` or \`miss\`. A miss means you changed something
native -- or that you are the first workspace on this commit, in which case build
once up front and the rest ride the cache.`;
  }
  return `Most changes touch no native input, and those should not compile anything.
The community CLI has no provider hook, so ask rn-iso directly:

\`\`\`bash
APP=$(npx rn-iso build-cache resolve --platform ios) || {
  ${facts.runCommand} --udid "$UDID" --port "$PORT"
  npx rn-iso build-cache store --platform ios --path "$BUILT_APP"
}
\`\`\`

It needs \`@expo/fingerprint\` (which works on a bare project) to compute the key:
\`npm i -D @expo/fingerprint\`.`;
}

export function renderWorkflow(facts) {
  return `# WORKFLOW.md

Take a task, produce a pull request. Two or three in flight at once.

Generated by \`rn-iso init\`. Edit freely -- it is a starting point, not managed.

## 1. Workspace

\`\`\`bash
WS=$(npx rn-iso worktree create task-123 --carry-ignored)
cd "$WS"
\`\`\`

A git worktree with every gitignored path cloned rather than reinstalled --
\`node_modules\`, \`ios/Pods\`, build codegen, \`.env\`. On APFS those are
copy-on-write, so it costs seconds and almost no real disk instead of an install
plus a pod install.

The main checkout is never touched. Nothing in the loop runs there.

Cloned dependencies match the source worktree, not this branch's manifests --
the same contract as restoring a CI cache. Reinstall if the branch changes them.

## 2. Device and Metro

\`\`\`bash
npx rn-iso up ios --json      # owned simulator + a reserved Metro port
npx expo start --port <port> > /tmp/rn-iso-metro-<port>.log 2>&1 &
\`\`\`

rn-iso reserves the port; it does not start Metro. Start it yourself from inside
the workspace, or teardown cannot identify it as yours. It is ready when
\`curl -s localhost:<port>/status\` answers \`packager-status:running\`.

Starting it separately rather than letting the run command spawn it is the whole
point: the output becomes a file you can grep at any time and that outlives the
build, instead of console output interleaved into whichever shell launched it.
The app's \`console.log\` arrives there over React Native's own logging channel,
so nothing is lost by not letting the run command own the bundler.

Name the log after the port, not the task: the port comes back from
\`up --json\` and from \`rn-iso status\`, so anything can find the log again
without being told where it went.

That file is also the app's console -- \`console.log\` from the running app
lands there -- and it is the fastest instrument you have for anything you need
to measure rather than look at.

${devClientSection(facts)}

## 3. Run

\`\`\`bash
${facts.runCommand} --device <udid> --port <port>
\`\`\`

Do not add \`--no-bundler\`, however reasonable it looks once you have started
Metro yourself: it is mutually exclusive with \`--port\` and the command exits
without building. The run command reuses a bundler already answering there.

${buildCacheSection(facts)}

## 4. Implement, validate, PR

Validate on the device. Screenshots for anything visual, before-and-after for
anything perceptual, both platforms when the task itself is cross-platform.
Capture the "before" evidence *before* you edit anything -- recovering it later
means stashing your fix and rebuilding the state you already had.

A perceptual problem still needs a number. Video proves the feel; it does not
measure.

## 5. Finish

\`\`\`bash
npx rn-iso worktree remove "$WS"
\`\`\`

Removes the worktree, its branch's environment, the owned simulator and this
workspace's Metro. It refuses if the worktree holds uncommitted changes or
commits that exist on no remote -- push first rather than forcing.

## Concurrency

Two or three workspaces, not ten. Each holds a simulator (1-2 GB) and a Metro
process; the binding constraint is RAM, and a machine that starts swapping is
slower than one working in sequence.

Builds do not need serialising: each workspace has its own derived data, and the
shared caches are content-addressed and append-only.

## Keeping it fast

\`\`\`bash
npx rn-iso doctor                                 # what is silently costing time
npx rn-iso gc --caches                            # what the caches have grown to
npx rn-iso gc --caches --delete --older-than 30   # trim what nothing has used
\`\`\`
`;
}

// A worktree carries every gitignored path by default, which is what makes it
// cheap -- but per-run output is pure noise in a fresh workspace and can be far
// larger than everything else combined.
export function renderWorktreeExclude() {
  return `# Paths not worth carrying into a new workspace (gitignore-style patterns).
# Everything else that is gitignored comes along, which is what makes
# \`worktree create --carry-ignored\` cheap.

# Per-run output: large, and meaningless in a fresh workspace.
**/*.log
coverage
`;
}

// The one script worth generating. `worktree create` and `worktree remove` are
// already commands, but the middle of the loop is a SEQUENCE -- reserve, start
// the bundler, wait for it, run against it -- and getting the order wrong fails
// in ways that do not name themselves: build before Metro answers and the app
// opens on a red screen, pass --no-bundler and the command exits without
// building.
//
// It lives in the consuming repo rather than inside rn-iso on purpose. Which
// build command a project needs is the judgement rn-iso refuses to take back,
// and a generated script is editable in a way a built-in command is not.
export function renderDevScript(facts) {
  // --client-logs is a community-CLI flag and has no Expo equivalent; Expo's
  // bundler already receives the app's console over React Native's own logging
  // channel, whoever started it.
  const startBundler = facts.isExpo ? 'npx expo start' : 'npx react-native start --client-logs';
  const runIos = facts.isExpo
    ? 'npx expo run:ios --device "$UDID" --port "$PORT"'
    : 'npx react-native run-ios --udid "$UDID" --port "$PORT"';

  // A bare app has no dev client to receive the deep link, so the port has to
  // reach it at runtime instead. Compiling it in would poison a
  // fingerprint-keyed build cache, which does not include the port.
  const portOverride = facts.isExpo
    ? ''
    : `
# Bare RN: the port is not compiled in and there is no dev client to receive it,
# so point the app at this workspace's bundler at runtime.
BUNDLE_ID=$(node -p "require('./app.json').expo?.ios?.bundleIdentifier || ''" 2>/dev/null || echo '')
if [ -n "$BUNDLE_ID" ]; then
  xcrun simctl spawn "$UDID" defaults write "$BUNDLE_ID" RCT_jsLocation "localhost:$PORT" || true
fi
`;

  return `#!/usr/bin/env bash
# Generated by \`rn-iso init\`. Edit freely.
#
# Reserve an environment, start this workspace's bundler, wait for it, and run
# against it. Order matters: build before Metro answers and the app opens on a
# red screen instead of your app.
set -euo pipefail

FACTS=$(npx rn-iso up ios --json | tail -1)
UDID=$(node -pe 'JSON.parse(process.argv[1]).udid' "$FACTS")
PORT=$(node -pe 'JSON.parse(process.argv[1]).metroPort' "$FACTS")

# Named after the port so anything can find it again from \`rn-iso status\`
# without being told where it went. It is also the app's console.
LOG="/tmp/rn-iso-metro-\${PORT}.log"

if curl -sf "http://localhost:\${PORT}/status" 2>/dev/null | grep -q packager-status:running; then
  echo "Metro already serving on \${PORT}" >&2
else
  # From inside the project directory, or teardown cannot prove the bundler is
  # ours and will refuse to kill it.
  ${startBundler} --port "$PORT" > "$LOG" 2>&1 &
  # Poll rather than sleep: it is ready in a couple of seconds, and a fixed
  # sleep is either a waste or a race.
  for _ in $(seq 1 60); do
    curl -sf "http://localhost:\${PORT}/status" 2>/dev/null | grep -q packager-status:running && break
    sleep 1
  done
fi
${portOverride}
# No --no-bundler here, however reasonable it looks: it is mutually exclusive
# with --port, and the command exits without building.
${runIos}

echo "" >&2
echo "Metro log: \${LOG}" >&2
`;
}
