// Generates the loop documentation a repo needs before several agents can work
// in it at once.
//
// Deliberately not a scaffolder for scripts: `worktree create --carry-ignored`
// and `worktree remove` already are the workspace lifecycle, so generating a
// wrapper around them would be code to maintain in every consuming repo. What a
// repo cannot get from `--help` is the ORDER, and the handful of traps that cost
// an afternoon each -- so that is what gets written down.
//
// Everything here is a pure function of facts about the project, so the template
// can be tested without touching a filesystem.

// Detected rather than assumed: the advice differs enough between an Expo app
// and a bare one that guessing would produce a document that is wrong in the
// places people actually get stuck.
export function projectFacts({ pkg, appConfig, hasPodfile }) {
  const deps = { ...(pkg?.dependencies || {}), ...(pkg?.devDependencies || {}) };
  const expoRange = deps.expo || null;
  const sdkMajor = expoRange
    ? parseInt(String(expoRange).replace(/[^\d.]/g, '').split('.')[0], 10) || null
    : null;
  return {
    name: appConfig?.expo?.name || pkg?.name || 'the app',
    isExpo: Boolean(expoRange),
    sdkMajor,
    hasDevClient: Boolean(deps['expo-dev-client']),
    hasPodfile: Boolean(hasPodfile),
    // The run command is the one thing rn-iso refuses to decide at runtime, so
    // the template states the project's own rather than inventing one.
    runCommand: expoRange ? 'npx expo run:ios' : 'npx react-native run-ios',
  };
}

function devClientSection(facts) {
  if (!facts.isExpo) {
    return `A reserved port reaches a bare React Native app through \`RCT_METRO_PORT\`
at build time or \`RCT_jsLocation\` at runtime. Prefer the runtime one: a build
cache keys on the native fingerprint, which does not include the port, so a
binary with a port compiled in can be handed to a workspace holding a different
one and will silently talk to the wrong bundler.

\`\`\`bash
xcrun simctl spawn <udid> defaults write <bundle-id> RCT_jsLocation "localhost:<port>"
\`\`\``;
  }
  if (facts.hasDevClient) {
    return `A reserved port only reaches the app because \`expo-dev-client\` is installed:
\`--port\` is never compiled into the binary, it travels in the deep link
\`run:ios\` opens. Keeping the port out of the binary is also what lets one
cached build serve workspaces holding different ports.`;
  }
  return `**Install \`expo-dev-client\` before anything else here works.** A reserved
port cannot reach the app without it -- \`--port\` travels in the deep link
\`run:ios\` opens, and with nothing handling that URL the app looks for Metro on
8081, finds nothing, and shows a red \`No script URL provided\`.

\`\`\`bash
npx expo install expo-dev-client
\`\`\``;
}

function buildCacheSection(facts) {
  if (facts.isExpo) {
    const key = facts.sdkMajor && facts.sdkMajor <= 53
      ? 'expo.experiments.buildCacheProvider'
      : 'expo.buildCacheProvider';
    return `Most changes touch no native input, and those should not compile anything.
\`@rn-iso/expo-build-cache\` keys a built \`.app\` on Expo's fingerprint of the
native inputs and installs it instead of building.

\`\`\`bash
npm i -D @rn-iso/expo-build-cache
\`\`\`

Point \`${key}\` at it in app.json. That key matters: SDK 53 reads only the
\`experiments\` one and ignores the top-level one in silence, while SDK 54+ reads
the top-level one and falls back to \`experiments\`.

Watch for \`[build-cache] hit\` or \`miss\`. A miss means you changed something
native -- or that you are the first workspace on this commit, in which case build
once up front and the rest ride the cache.`;
  }
  return `Most changes touch no native input, and those should not compile anything.
The community CLI has no provider hook, so ask rn-iso directly:

\`\`\`bash
APP=$(npx rn-iso build-cache resolve --platform ios) || {
  ${facts.runCommand} --udid "$UDID" --port "$PORT"
  npx rn-iso build-cache store --platform ios --path "$BUILT_APP"
}
\`\`\`

It needs \`@expo/fingerprint\` (which works on a bare project) to compute the key:
\`npm i -D @expo/fingerprint\`.`;
}

export function renderWorkflow(facts) {
  return `# WORKFLOW.md

Take a task, produce a pull request. Two or three in flight at once.

Generated by \`rn-iso init\`. Edit freely -- it is a starting point, not managed.

## 1. Workspace

\`\`\`bash
WS=$(npx rn-iso worktree create task-123 --carry-ignored)
cd "$WS"
\`\`\`

A git worktree with every gitignored path cloned rather than reinstalled --
\`node_modules\`, \`ios/Pods\`, build codegen, \`.env\`. On APFS those are
copy-on-write, so it costs seconds and almost no real disk instead of an install
plus a pod install.

The main checkout is never touched. Nothing in the loop runs there.

Cloned dependencies match the source worktree, not this branch's manifests --
the same contract as restoring a CI cache. Reinstall if the branch changes them.

## 2. Device and Metro

\`\`\`bash
npx rn-iso up ios --json      # owned simulator + a reserved Metro port
npx expo start --port <port> > /tmp/metro-task-123.log 2>&1 &
\`\`\`

rn-iso reserves the port; it does not start Metro. Start it yourself from inside
the workspace, or teardown cannot identify it as yours. It is ready when
\`curl -s localhost:<port>/status\` answers \`packager-status:running\`.

That log file is also the app's console: \`console.log\` from the running app
lands there, and it is the fastest instrument you have for anything you need to
measure rather than look at.

${devClientSection(facts)}

## 3. Run

\`\`\`bash
${facts.runCommand} --device <udid> --port <port>
\`\`\`

Do not add \`--no-bundler\`, however reasonable it looks once you have started
Metro yourself: it is mutually exclusive with \`--port\` and the command exits
without building. The run command reuses a bundler already answering there.

${buildCacheSection(facts)}

## 4. Implement, validate, PR

Validate on the device. Screenshots for anything visual, before-and-after for
anything perceptual, both platforms when the task itself is cross-platform.
Capture the "before" evidence *before* you edit anything -- recovering it later
means stashing your fix and rebuilding the state you already had.

A perceptual problem still needs a number. Video proves the feel; it does not
measure.

## 5. Finish

\`\`\`bash
npx rn-iso worktree remove "$WS"
\`\`\`

Removes the worktree, its branch's environment, the owned simulator and this
workspace's Metro. It refuses if the worktree holds uncommitted changes or
commits that exist on no remote -- push first rather than forcing.

## Concurrency

Two or three workspaces, not ten. Each holds a simulator (1-2 GB) and a Metro
process; the binding constraint is RAM, and a machine that starts swapping is
slower than one working in sequence.

Builds do not need serialising: each workspace has its own derived data, and the
shared caches are content-addressed and append-only.

## Keeping it fast

\`\`\`bash
npx rn-iso doctor                                 # what is silently costing time
npx rn-iso gc --caches                            # what the caches have grown to
npx rn-iso gc --caches --delete --older-than 30   # trim what nothing has used
\`\`\`
`;
}

// A worktree carries every gitignored path by default, which is what makes it
// cheap -- but per-run output is pure noise in a fresh workspace and can be far
// larger than everything else combined.
export function renderWorktreeExclude() {
  return `# Paths not worth carrying into a new workspace (gitignore-style patterns).
# Everything else that is gitignored comes along, which is what makes
# \`worktree create --carry-ignored\` cheap.

# Per-run output: large, and meaningless in a fresh workspace.
**/*.log
coverage
`;
}
